# Generated by Django 2.1.2 on 2019-01-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='rank',
            field=models.CharField(default=-99, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='weight',
            field=models.IntegerField(default=-99),
            preserve_default=False,
        ),
    ]
